uploads = []
generated = []

[[outputs]]
id = "XSwgvMJK89UrJywad7Mtp"
uri = "file://UMI_Improvements.md"
type = "text"
title = "UMI Improvement Backlog"

[[outputs]]
id = "Cj2GYMIDoOzDLS4zJTutG"
uri = "file://UMI Improvements.md"
type = "text"
title = "UMI Improvements.md"
