// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/splash/SplashScreen.tsx": () => import("../components/mockups/splash/SplashScreen.tsx"),
  "./components/mockups/umi-app/History.tsx": () => import("../components/mockups/umi-app/History.tsx"),
  "./components/mockups/umi-app/Interpreter.tsx": () => import("../components/mockups/umi-app/Interpreter.tsx"),
  "./components/mockups/umi-app/SessionDetail.tsx": () => import("../components/mockups/umi-app/SessionDetail.tsx"),
  "./components/mockups/umi-app/Setup.tsx": () => import("../components/mockups/umi-app/Setup.tsx")
};
